In [1]:
import polars as pl

columns = ['_from', '_to', 'from', 'to', 'number', 'remark', 'resembling', 'type']
main = pl.read_csv('relationships_main.csv', new_columns=columns)
refactored = pl.read_csv('relationships_refactored.csv', new_columns=columns)

In [5]:
main.filter(main.is_duplicated())

shape: (963, 8)
┌───────────────┬───────────────┬──────────────┬─────────────┬────────┬────────┬────────────┬──────┐
│ _from         ┆ _to           ┆ from         ┆ to          ┆ number ┆ remark ┆ resembling ┆ type │
│ ---           ┆ ---           ┆ ---          ┆ ---         ┆ ---    ┆ ---    ┆ ---        ┆ ---  │
│ str           ┆ str           ┆ str          ┆ str         ┆ i64    ┆ str    ┆ bool       ┆ str  │
╞═══════════════╪═══════════════╪══════════════╪═════════════╪════════╪════════╪════════════╪══════╡
│ super_nav_det ┆ super_nav_det ┆ an5.100#6.1- ┆ pli         ┆ 1      ┆ null   ┆ false      ┆ full │
│ ails/an5.100  ┆ ails/pli-tv-k ┆ #11.1        ┆             ┆        ┆        ┆            ┆      │
│               ┆ d17           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ an5.100#6.1- ┆ pli         ┆ 1      ┆ null   ┆ false      ┆ full │
│ ails/an5.100  ┆ ails/pli-tv-k ┆ #11.1        ┆             ┆        ┆        ┆            ┆      │
│               ┆ d17           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ an8.20       ┆ lzh         ┆ 20     ┆ null   ┆ false      ┆ full │
│ ails/an8.20   ┆ ails/lzh-sarv ┆              ┆             ┆        ┆        ┆            ┆      │
│               ┆ -kd1…         ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ an8.20       ┆ lzh         ┆ 20     ┆ null   ┆ false      ┆ full │
│ ails/an8.20   ┆ ails/lzh-sarv ┆              ┆             ┆        ┆        ┆            ┆      │
│               ┆ -kd1…         ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ an8.65#1.1   ┆ an1.439#1.1 ┆ 1      ┆ null   ┆ true       ┆ full │
│ ails/an8.65   ┆ ails/an1.394- ┆              ┆             ┆        ┆        ┆            ┆      │
│               ┆ 574           ┆              ┆             ┆        ┆        ┆            ┆      │
│ …             ┆ …             ┆ …            ┆ …           ┆ …      ┆ …      ┆ …          ┆ …    │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-bu-vb ┆ pli         ┆ 18     ┆ null   ┆ true       ┆ full │
│ ails/xct-mu-b ┆ ails/pli-tv-k ┆ -np18        ┆             ┆        ┆        ┆            ┆      │
│ u-vb…         ┆ d22           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-bu-vb ┆ pli         ┆ 34     ┆ null   ┆ true       ┆ full │
│ ails/xct-mu-b ┆ ails/pli-tv-k ┆ -pc34        ┆             ┆        ┆        ┆            ┆      │
│ u-vb…         ┆ d22           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-bu-vb ┆ pli         ┆ 34     ┆ null   ┆ true       ┆ full │
│ ails/xct-mu-b ┆ ails/pli-tv-k ┆ -pc34        ┆             ┆        ┆        ┆            ┆      │
│ u-vb…         ┆ d22           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-kd14  ┆ lzh         ┆ 14     ┆ null   ┆ false      ┆ full │
│ ails/xct-mu-k ┆ ails/lzh-sarv ┆              ┆             ┆        ┆        ┆            ┆      │
│ d14           ┆ -kd1…         ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-kd14  ┆ lzh         ┆ 14     ┆ null   ┆ false      ┆ full │
│ ails/xct-mu-k ┆ ails/lzh-sarv ┆              ┆             ┆        ┆        ┆            ┆      │
│ d14           ┆ -kd1…         ┆              ┆             ┆        ┆        ┆            ┆      │
└───────────────┴───────────────┴──────────────┴─────────────┴────────┴────────┴────────────┴──────┘

In [6]:
refactored.filter(refactored.is_duplicated())

shape: (955, 8)
┌───────────────┬───────────────┬──────────────┬─────────────┬────────┬────────┬────────────┬──────┐
│ _from         ┆ _to           ┆ from         ┆ to          ┆ number ┆ remark ┆ resembling ┆ type │
│ ---           ┆ ---           ┆ ---          ┆ ---         ┆ ---    ┆ ---    ┆ ---        ┆ ---  │
│ str           ┆ str           ┆ str          ┆ str         ┆ i64    ┆ str    ┆ bool       ┆ str  │
╞═══════════════╪═══════════════╪══════════════╪═════════════╪════════╪════════╪════════════╪══════╡
│ super_nav_det ┆ super_nav_det ┆ an5.100#6.1- ┆ pli         ┆ 1      ┆ null   ┆ false      ┆ full │
│ ails/an5.100  ┆ ails/pli-tv-k ┆ #11.1        ┆             ┆        ┆        ┆            ┆      │
│               ┆ d17           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ an5.100#6.1- ┆ pli         ┆ 1      ┆ null   ┆ false      ┆ full │
│ ails/an5.100  ┆ ails/pli-tv-k ┆ #11.1        ┆             ┆        ┆        ┆            ┆      │
│               ┆ d17           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ an8.20       ┆ lzh         ┆ 20     ┆ null   ┆ false      ┆ full │
│ ails/an8.20   ┆ ails/lzh-sarv ┆              ┆             ┆        ┆        ┆            ┆      │
│               ┆ -kd1…         ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ an8.20       ┆ lzh         ┆ 20     ┆ null   ┆ false      ┆ full │
│ ails/an8.20   ┆ ails/lzh-sarv ┆              ┆             ┆        ┆        ┆            ┆      │
│               ┆ -kd1…         ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ an8.65#1.1   ┆ an1.439#1.1 ┆ 1      ┆ null   ┆ true       ┆ full │
│ ails/an8.65   ┆ ails/an1.394- ┆              ┆             ┆        ┆        ┆            ┆      │
│               ┆ 574           ┆              ┆             ┆        ┆        ┆            ┆      │
│ …             ┆ …             ┆ …            ┆ …           ┆ …      ┆ …      ┆ …          ┆ …    │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-bu-vb ┆ pli         ┆ 18     ┆ null   ┆ true       ┆ full │
│ ails/xct-mu-b ┆ ails/pli-tv-k ┆ -np18        ┆             ┆        ┆        ┆            ┆      │
│ u-vb…         ┆ d22           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-bu-vb ┆ pli         ┆ 34     ┆ null   ┆ true       ┆ full │
│ ails/xct-mu-b ┆ ails/pli-tv-k ┆ -pc34        ┆             ┆        ┆        ┆            ┆      │
│ u-vb…         ┆ d22           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-bu-vb ┆ pli         ┆ 34     ┆ null   ┆ true       ┆ full │
│ ails/xct-mu-b ┆ ails/pli-tv-k ┆ -pc34        ┆             ┆        ┆        ┆            ┆      │
│ u-vb…         ┆ d22           ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-kd14  ┆ lzh         ┆ 14     ┆ null   ┆ false      ┆ full │
│ ails/xct-mu-k ┆ ails/lzh-sarv ┆              ┆             ┆        ┆        ┆            ┆      │
│ d14           ┆ -kd1…         ┆              ┆             ┆        ┆        ┆            ┆      │
│ super_nav_det ┆ super_nav_det ┆ xct-mu-kd14  ┆ lzh         ┆ 14     ┆ null   ┆ false      ┆ full │
│ ails/xct-mu-k ┆ ails/lzh-sarv ┆              ┆             ┆        ┆        ┆            ┆      │
│ d14           ┆ -kd1…         ┆              ┆             ┆        ┆        ┆            ┆      │
└───────────────┴───────────────┴──────────────┴─────────────┴────────┴────────┴────────────┴──────┘

Seems we have duplicates.

In [9]:
main.join(refactored, on=['_from', '_to', 'from', 'to', 'number', 'remark', 'resembling', 'type'], how='anti')

shape: (421_059, 8)
┌────────────────┬───────────────┬─────────────┬──────────┬────────┬────────┬────────────┬─────────┐
│ _from          ┆ _to           ┆ from        ┆ to       ┆ number ┆ remark ┆ resembling ┆ type    │
│ ---            ┆ ---           ┆ ---         ┆ ---      ┆ ---    ┆ ---    ┆ ---        ┆ ---     │
│ str            ┆ str           ┆ str         ┆ str      ┆ i64    ┆ str    ┆ bool       ┆ str     │
╞════════════════╪═══════════════╪═════════════╪══════════╪════════╪════════╪════════════╪═════════╡
│ super_nav_deta ┆ super_nav_det ┆ an1.6-10    ┆ ea9.8    ┆ 10     ┆ null   ┆ false      ┆ full    │
│ ils/an1.1-10   ┆ ails/ea9.8    ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ an1.1-5     ┆ t792     ┆ 5      ┆ null   ┆ false      ┆ full    │
│ ils/an1.1-10   ┆ ails/t792     ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ an1.16-20   ┆ ea9.10   ┆ 20     ┆ null   ┆ false      ┆ full    │
│ ils/an1.11-20  ┆ ails/ea9.10   ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ an1.11-15   ┆ ea9.9    ┆ 15     ┆ null   ┆ false      ┆ full    │
│ ils/an1.11-20  ┆ ails/ea9.9    ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ an1.17#1.1  ┆ pe3#27.1 ┆ 1      ┆ null   ┆ false      ┆ mention │
│ ils/an1.11-20  ┆ ails/pe3      ┆             ┆          ┆        ┆        ┆            ┆         │
│ …              ┆ …             ┆ …           ┆ …        ┆ …      ┆ …      ┆ …          ┆ …       │
│ super_nav_deta ┆ super_nav_det ┆ xct-mu-kd9  ┆ lzh      ┆ 9      ┆ null   ┆ false      ┆ full    │
│ ils/xct-mu-kd9 ┆ ails/lzh-mu-k ┆             ┆          ┆        ┆        ┆            ┆         │
│                ┆ d9            ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ xct-mu-kd9  ┆ lzh      ┆ 9      ┆ null   ┆ false      ┆ full    │
│ ils/xct-mu-kd9 ┆ ails/lzh-sarv ┆             ┆          ┆        ┆        ┆            ┆         │
│                ┆ -kd9          ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ xct-mu-kd9  ┆ pli      ┆ 9      ┆ null   ┆ false      ┆ full    │
│ ils/xct-mu-kd9 ┆ ails/pli-tv-k ┆             ┆          ┆        ┆        ┆            ┆         │
│                ┆ d10           ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ xct-mu-kd9  ┆ san      ┆ 9      ┆ null   ┆ false      ┆ full    │
│ ils/xct-mu-kd9 ┆ ails/san-mu-k ┆             ┆          ┆        ┆        ┆            ┆         │
│                ┆ d9            ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ ya3.1.1#1.1 ┆ arv4     ┆ 1      ┆ null   ┆ false      ┆ mention │
│ ils/ya3.1.1    ┆ ails/arv4     ┆             ┆          ┆        ┆        ┆            ┆         │
└────────────────┴───────────────┴─────────────┴──────────┴────────┴────────┴────────────┴─────────┘

In [14]:
from edges import get_data

In [15]:
df = get_data()

In [16]:
df

shape: (842_196, 8)
┌────────────────┬───────────────┬─────────────┬──────────┬────────┬────────┬────────────┬─────────┐
│ _from          ┆ _to           ┆ from        ┆ to       ┆ number ┆ remark ┆ resembling ┆ type    │
│ ---            ┆ ---           ┆ ---         ┆ ---      ┆ ---    ┆ ---    ┆ ---        ┆ ---     │
│ str            ┆ str           ┆ str         ┆ str      ┆ i64    ┆ str    ┆ bool       ┆ str     │
╞════════════════╪═══════════════╪═════════════╪══════════╪════════╪════════╪════════════╪═════════╡
│ super_nav_deta ┆ super_nav_det ┆ an1.6-10    ┆ ea9.8    ┆ 10     ┆ null   ┆ false      ┆ full    │
│ ils/an1.1-10   ┆ ails/ea9.8    ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ an1.1-5     ┆ t792     ┆ 5      ┆ null   ┆ false      ┆ full    │
│ ils/an1.1-10   ┆ ails/t792     ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ an1.16-20   ┆ ea9.10   ┆ 20     ┆ null   ┆ false      ┆ full    │
│ ils/an1.11-20  ┆ ails/ea9.10   ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ an1.11-15   ┆ ea9.9    ┆ 15     ┆ null   ┆ false      ┆ full    │
│ ils/an1.11-20  ┆ ails/ea9.9    ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ an1.17#1.1  ┆ pe3#27.1 ┆ 1      ┆ null   ┆ false      ┆ mention │
│ ils/an1.11-20  ┆ ails/pe3      ┆             ┆          ┆        ┆        ┆            ┆         │
│ …              ┆ …             ┆ …           ┆ …        ┆ …      ┆ …      ┆ …          ┆ …       │
│ super_nav_deta ┆ super_nav_det ┆ xct-mu-kd9  ┆ lzh      ┆ 9      ┆ null   ┆ false      ┆ full    │
│ ils/xct-mu-kd9 ┆ ails/lzh-mu-k ┆             ┆          ┆        ┆        ┆            ┆         │
│                ┆ d9            ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ xct-mu-kd9  ┆ lzh      ┆ 9      ┆ null   ┆ false      ┆ full    │
│ ils/xct-mu-kd9 ┆ ails/lzh-sarv ┆             ┆          ┆        ┆        ┆            ┆         │
│                ┆ -kd9          ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ xct-mu-kd9  ┆ pli      ┆ 9      ┆ null   ┆ false      ┆ full    │
│ ils/xct-mu-kd9 ┆ ails/pli-tv-k ┆             ┆          ┆        ┆        ┆            ┆         │
│                ┆ d10           ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ xct-mu-kd9  ┆ san      ┆ 9      ┆ null   ┆ false      ┆ full    │
│ ils/xct-mu-kd9 ┆ ails/san-mu-k ┆             ┆          ┆        ┆        ┆            ┆         │
│                ┆ d9            ┆             ┆          ┆        ┆        ┆            ┆         │
│ super_nav_deta ┆ super_nav_det ┆ ya3.1.1#1.1 ┆ arv4     ┆ 1      ┆ null   ┆ false      ┆ mention │
│ ils/ya3.1.1    ┆ ails/arv4     ┆             ┆          ┆        ┆        ┆            ┆         │
└────────────────┴───────────────┴─────────────┴──────────┴────────┴────────┴────────────┴─────────┘