In [7]:
import polars as pl
from edges import combine, branch_count, in_both_branches, resembling_mentions

In [8]:
df = combine()

In [9]:
df = df.with_columns(
        in_both_branches(branch_count()).alias('in_both')
    )

In [4]:
df.filter(~pl.col('in_both') & pl.col('branch').eq('main'))

shape: (1_468, 10)
┌─────────────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬────────┬─────────┐
│ _from       ┆ _to        ┆ from       ┆ to         ┆ … ┆ resembling ┆ type    ┆ branch ┆ in_both │
│ ---         ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---     ┆ ---    ┆ ---     │
│ str         ┆ str        ┆ str        ┆ str        ┆   ┆ bool       ┆ str     ┆ str    ┆ bool    │
╞═════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════╪═════════╡
│ super_nav_d ┆ super_nav_ ┆ an1.219-23 ┆ ~mil5.5.3# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an1. ┆ details/mi ┆ 4#1.1      ┆ 1.1        ┆   ┆            ┆         ┆        ┆         │
│ 219-234     ┆ l5.5.3     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an1.616#1. ┆ ~mil6.4.1# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an1. ┆ details/mi ┆ 1          ┆ 20.1       ┆   ┆            ┆         ┆        ┆         │
│ 616-627     ┆ l6.4.1     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an10.89#1. ┆ ~ne37#53.1 ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an10 ┆ details/ne ┆ 1-#10.1    ┆ -#58.1     ┆   ┆            ┆         ┆        ┆         │
│ .89         ┆ 37         ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an3.131#1. ┆ ~mil5.4.2# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an3. ┆ details/mi ┆ 1-#2.1     ┆ 1.1        ┆   ┆            ┆         ┆        ┆         │
│ 131         ┆ l5.4.2     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an3.36#13. ┆ ~mil3.4.6# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an3. ┆ details/mi ┆ 1-#15.1    ┆ 2.1        ┆   ┆            ┆         ┆        ┆         │
│ 36          ┆ l3.4.6     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ …           ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …       ┆ …      ┆ …       │
│ super_nav_d ┆ super_nav_ ┆ uvs7#uvs7. ┆ ~mil5.3.3# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/uvs7 ┆ details/mi ┆ 7          ┆ 2.1        ┆   ┆            ┆         ┆        ┆         │
│             ┆ l5.3.3     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ xct-mu-bi- ┆ ~kv21.4#6. ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/xct- ┆ details/kv ┆ pm-np19    ┆ 1          ┆   ┆            ┆         ┆        ┆         │
│ mu-bi-pm…   ┆ 21.4       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ xct-mu-bi- ┆ ~kv21.4#6. ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/xct- ┆ details/kv ┆ vb-np19    ┆ 1          ┆   ┆            ┆         ┆        ┆         │
│ mu-bi-vb…   ┆ 21.4       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ xct-mu-bu- ┆ ~kv21.4#6. ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/xct- ┆ details/kv ┆ pm-np30    ┆ 1          ┆   ┆            ┆         ┆        ┆         │
│ mu-bu-pm…   ┆ 21.4       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ xct-mu-bu- ┆ ~kv21.4#6. ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/xct- ┆ details/kv ┆ vb-np30    ┆ 1          ┆   ┆            ┆         ┆        ┆         │
│ mu-bu-vb…   ┆ 21.4       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
└─────────────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴────────┴─────────┘

In [5]:
df.filter(~pl.col('in_both') & pl.col('branch').eq('refactored'))

shape: (1_348, 10)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬───────────┬─────────┐
│ _from      ┆ _to        ┆ from       ┆ to        ┆ … ┆ resemblin ┆ type    ┆ branch    ┆ in_both │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ g         ┆ ---     ┆ ---       ┆ ---     │
│ str        ┆ str        ┆ str        ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ bool    │
│            ┆            ┆            ┆           ┆   ┆ bool      ┆         ┆           ┆         │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═════════╡
│ super_nav_ ┆ super_nav_ ┆ an1.219-23 ┆ mil5.5.3# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/mi ┆ 4#1.1      ┆ 1.1       ┆   ┆           ┆         ┆ d         ┆         │
│ 1.219-234  ┆ l5.5.3     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an1.616#1. ┆ mil6.4.1# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/mi ┆ 1          ┆ 20.1      ┆   ┆           ┆         ┆ d         ┆         │
│ 1.616-627  ┆ l6.4.1     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an10.89#1. ┆ ne37#53.1 ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/ne ┆ 1-#10.1    ┆ -#58.1    ┆   ┆           ┆         ┆ d         ┆         │
│ 10.89      ┆ 37         ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an3.131#1. ┆ mil5.4.2# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/mi ┆ 1-#2.1     ┆ 1.1       ┆   ┆           ┆         ┆ d         ┆         │
│ 3.131      ┆ l5.4.2     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an3.36#13. ┆ mil3.4.6# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/mi ┆ 1-#15.1    ┆ 2.1       ┆   ┆           ┆         ┆ d         ┆         │
│ 3.36       ┆ l3.4.6     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …       │
│ super_nav_ ┆ super_nav_ ┆ uvs7#uvs7. ┆ mil5.3.3# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/uv ┆ details/mi ┆ 7          ┆ 2.1       ┆   ┆           ┆         ┆ d         ┆         │
│ s7         ┆ l5.3.3     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bi- ┆ kv21.4#6. ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/xc ┆ details/kv ┆ pm-np19    ┆ 1         ┆   ┆           ┆         ┆ d         ┆         │
│ t-mu-bi-pm ┆ 21.4       ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆            ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bi- ┆ kv21.4#6. ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/xc ┆ details/kv ┆ vb-np19    ┆ 1         ┆   ┆           ┆         ┆ d         ┆         │
│ t-mu-bi-vb ┆ 21.4       ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆            ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ kv21.4#6. ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/xc ┆ details/kv ┆ pm-np30    ┆ 1         ┆   ┆           ┆         ┆ d         ┆         │
│ t-mu-bu-pm ┆ 21.4       ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆            ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ kv21.4#6. ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/xc ┆ details/kv ┆ vb-np30    ┆ 1         ┆   ┆           ┆         ┆ d         ┆         │
│ t-mu-bu-vb ┆ 21.4       ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆            ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴───────────┴─────────┘

In [6]:
df.filter(
    ~pl.col('in_both')
).filter(
    pl.col('branch') == 'refactored'
).filter(
    ~(pl.col('resembling') & pl.col('type') == 'mention')
)

InvalidOperationError: `bitand` operation not supported for dtype `str`

This error occurred in the following expression:
	[(col("resembling").cast(String)) & (col("type"))]
while evaluating this larger expression:
	[([(col("resembling").cast(String)) & (col("type"))]) != ("mention")]