In [4]:
import polars as pl
from edges import combine

In [5]:
df = combine()

# What edges exist in `main` but not `refactored`?

- Filter on `branch` == `main`
- Is there a row that is the same, but with `branch` == `refactored`

In [6]:
df.describe()

shape: (9, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ _from     ┆ _to       ┆ from      ┆ … ┆ remark    ┆ resemblin ┆ type      ┆ branch   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ g         ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 842196    ┆ 842196    ┆ 842196    ┆ … ┆ 198       ┆ 842196.0  ┆ 842196    ┆ 842196   │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 841998    ┆ 0.0       ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.071105  ┆ null      ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ min       ┆ super_nav ┆ super_nav ┆ an1.1-5   ┆ … ┆ Akanuma   ┆ 0.0       ┆ full      ┆ main     │
│           ┆ _details/ ┆ _details/ ┆           ┆   ┆ p. 163    ┆           ┆           ┆          │
│           ┆ an1.1-10  ┆ an1.1-10  ┆           ┆   ┆ lists EA  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 49.5 a…   ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ super_nav ┆ super_nav ┆ ~thi-ap36 ┆ … ┆ This text ┆ 1.0       ┆ retelling ┆ refactor │
│           ┆ _details/ ┆ _details/ ┆ #16.1     ┆   ┆ is from   ┆           ┆           ┆ ed       │
│           ┆ ya3.1.1   ┆ ya3.1.1   ┆           ┆   ┆ the Jaina ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ca…       ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
df.with_columns(
    pl.struct(pl.exclude('branch')).n_unique().over('branch').alias('branch_count')
)

shape: (842_196, 10)
┌────────────┬────────────┬───────────┬──────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ _from      ┆ _to        ┆ from      ┆ to       ┆ … ┆ resemblin ┆ type    ┆ branch    ┆ branch_co │
│ ---        ┆ ---        ┆ ---       ┆ ---      ┆   ┆ g         ┆ ---     ┆ ---       ┆ unt       │
│ str        ┆ str        ┆ str       ┆ str      ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆            ┆           ┆          ┆   ┆ bool      ┆         ┆           ┆ u32       │
╞════════════╪════════════╪═══════════╪══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ super_nav_ ┆ super_nav_ ┆ an1.6-10  ┆ ea9.8    ┆ … ┆ false     ┆ full    ┆ main      ┆ 420621    │
│ details/an ┆ details/ea ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.1-10     ┆ 9.8        ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ an1.1-5   ┆ t792     ┆ … ┆ false     ┆ full    ┆ main      ┆ 420621    │
│ details/an ┆ details/t7 ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.1-10     ┆ 92         ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ an1.16-20 ┆ ea9.10   ┆ … ┆ false     ┆ full    ┆ main      ┆ 420621    │
│ details/an ┆ details/ea ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.11-20    ┆ 9.10       ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ an1.11-15 ┆ ea9.9    ┆ … ┆ false     ┆ full    ┆ main      ┆ 420621    │
│ details/an ┆ details/ea ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.11-20    ┆ 9.9        ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ an1.17#1. ┆ pe3#27.1 ┆ … ┆ false     ┆ mention ┆ main      ┆ 420621    │
│ details/an ┆ details/pe ┆ 1         ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.11-20    ┆ 3          ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …        ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-kd ┆ lzh      ┆ … ┆ false     ┆ full    ┆ refactore ┆ 420505    │
│ details/xc ┆ details/lz ┆ 9         ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ t-mu-kd9   ┆ h-mu-kd9   ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-kd ┆ lzh      ┆ … ┆ false     ┆ full    ┆ refactore ┆ 420505    │
│ details/xc ┆ details/lz ┆ 9         ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ t-mu-kd9   ┆ h-sarv-kd9 ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-kd ┆ pli      ┆ … ┆ false     ┆ full    ┆ refactore ┆ 420505    │
│ details/xc ┆ details/pl ┆ 9         ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ t-mu-kd9   ┆ i-tv-kd10  ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-kd ┆ san      ┆ … ┆ false     ┆ full    ┆ refactore ┆ 420505    │
│ details/xc ┆ details/sa ┆ 9         ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ t-mu-kd9   ┆ n-mu-kd9   ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ ya3.1.1#1 ┆ arv4     ┆ … ┆ false     ┆ mention ┆ refactore ┆ 420505    │
│ details/ya ┆ details/ar ┆ .1        ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ 3.1.1      ┆ v4         ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
└────────────┴────────────┴───────────┴──────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [24]:
df.with_columns(
    pl.col('branch').n_unique().over(pl.struct(pl.exclude('branch'))).alias('branch_count')
)

shape: (842_196, 10)
┌────────────┬────────────┬───────────┬──────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ _from      ┆ _to        ┆ from      ┆ to       ┆ … ┆ resemblin ┆ type    ┆ branch    ┆ branch_co │
│ ---        ┆ ---        ┆ ---       ┆ ---      ┆   ┆ g         ┆ ---     ┆ ---       ┆ unt       │
│ str        ┆ str        ┆ str       ┆ str      ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆            ┆           ┆          ┆   ┆ bool      ┆         ┆           ┆ u32       │
╞════════════╪════════════╪═══════════╪══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ super_nav_ ┆ super_nav_ ┆ an1.6-10  ┆ ea9.8    ┆ … ┆ false     ┆ full    ┆ main      ┆ 2         │
│ details/an ┆ details/ea ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.1-10     ┆ 9.8        ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ an1.1-5   ┆ t792     ┆ … ┆ false     ┆ full    ┆ main      ┆ 2         │
│ details/an ┆ details/t7 ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.1-10     ┆ 92         ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ an1.16-20 ┆ ea9.10   ┆ … ┆ false     ┆ full    ┆ main      ┆ 2         │
│ details/an ┆ details/ea ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.11-20    ┆ 9.10       ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ an1.11-15 ┆ ea9.9    ┆ … ┆ false     ┆ full    ┆ main      ┆ 2         │
│ details/an ┆ details/ea ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.11-20    ┆ 9.9        ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ an1.17#1. ┆ pe3#27.1 ┆ … ┆ false     ┆ mention ┆ main      ┆ 2         │
│ details/an ┆ details/pe ┆ 1         ┆          ┆   ┆           ┆         ┆           ┆           │
│ 1.11-20    ┆ 3          ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …        ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-kd ┆ lzh      ┆ … ┆ false     ┆ full    ┆ refactore ┆ 2         │
│ details/xc ┆ details/lz ┆ 9         ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ t-mu-kd9   ┆ h-mu-kd9   ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-kd ┆ lzh      ┆ … ┆ false     ┆ full    ┆ refactore ┆ 2         │
│ details/xc ┆ details/lz ┆ 9         ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ t-mu-kd9   ┆ h-sarv-kd9 ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-kd ┆ pli      ┆ … ┆ false     ┆ full    ┆ refactore ┆ 2         │
│ details/xc ┆ details/pl ┆ 9         ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ t-mu-kd9   ┆ i-tv-kd10  ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-kd ┆ san      ┆ … ┆ false     ┆ full    ┆ refactore ┆ 2         │
│ details/xc ┆ details/sa ┆ 9         ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ t-mu-kd9   ┆ n-mu-kd9   ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
│ super_nav_ ┆ super_nav_ ┆ ya3.1.1#1 ┆ arv4     ┆ … ┆ false     ┆ mention ┆ refactore ┆ 2         │
│ details/ya ┆ details/ar ┆ .1        ┆          ┆   ┆           ┆         ┆ d         ┆           │
│ 3.1.1      ┆ v4         ┆           ┆          ┆   ┆           ┆         ┆           ┆           │
└────────────┴────────────┴───────────┴──────────┴───┴───────────┴─────────┴───────────┴───────────┘