In [2]:
import polars as pl
from edges import combine, branch_count, in_both_branches, resembling_mentions

In [3]:
df = combine()

In [4]:
df = df.with_columns(
        in_both_branches(branch_count()).alias('in_both')
    )

In [5]:
df.filter(~pl.col('in_both') & pl.col('branch').eq('main'))

shape: (1_468, 10)
┌─────────────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬────────┬─────────┐
│ _from       ┆ _to        ┆ from       ┆ to         ┆ … ┆ resembling ┆ type    ┆ branch ┆ in_both │
│ ---         ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---     ┆ ---    ┆ ---     │
│ str         ┆ str        ┆ str        ┆ str        ┆   ┆ bool       ┆ str     ┆ str    ┆ bool    │
╞═════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════╪═════════╡
│ super_nav_d ┆ super_nav_ ┆ an1.219-23 ┆ ~mil5.5.3# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an1. ┆ details/mi ┆ 4#1.1      ┆ 1.1        ┆   ┆            ┆         ┆        ┆         │
│ 219-234     ┆ l5.5.3     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an1.616#1. ┆ ~mil6.4.1# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an1. ┆ details/mi ┆ 1          ┆ 20.1       ┆   ┆            ┆         ┆        ┆         │
│ 616-627     ┆ l6.4.1     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an10.89#1. ┆ ~ne37#53.1 ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an10 ┆ details/ne ┆ 1-#10.1    ┆ -#58.1     ┆   ┆            ┆         ┆        ┆         │
│ .89         ┆ 37         ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an3.131#1. ┆ ~mil5.4.2# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an3. ┆ details/mi ┆ 1-#2.1     ┆ 1.1        ┆   ┆            ┆         ┆        ┆         │
│ 131         ┆ l5.4.2     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an3.36#13. ┆ ~mil3.4.6# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an3. ┆ details/mi ┆ 1-#15.1    ┆ 2.1        ┆   ┆            ┆         ┆        ┆         │
│ 36          ┆ l3.4.6     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ …           ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …       ┆ …      ┆ …       │
│ super_nav_d ┆ super_nav_ ┆ uvs7#uvs7. ┆ ~mil5.3.3# ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/uvs7 ┆ details/mi ┆ 7          ┆ 2.1        ┆   ┆            ┆         ┆        ┆         │
│             ┆ l5.3.3     ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ xct-mu-bi- ┆ ~kv21.4#6. ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/xct- ┆ details/kv ┆ pm-np19    ┆ 1          ┆   ┆            ┆         ┆        ┆         │
│ mu-bi-pm…   ┆ 21.4       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ xct-mu-bi- ┆ ~kv21.4#6. ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/xct- ┆ details/kv ┆ vb-np19    ┆ 1          ┆   ┆            ┆         ┆        ┆         │
│ mu-bi-vb…   ┆ 21.4       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ xct-mu-bu- ┆ ~kv21.4#6. ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/xct- ┆ details/kv ┆ pm-np30    ┆ 1          ┆   ┆            ┆         ┆        ┆         │
│ mu-bu-pm…   ┆ 21.4       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ xct-mu-bu- ┆ ~kv21.4#6. ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/xct- ┆ details/kv ┆ vb-np30    ┆ 1          ┆   ┆            ┆         ┆        ┆         │
│ mu-bu-vb…   ┆ 21.4       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
└─────────────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴────────┴─────────┘

In [6]:
df.filter(~pl.col('in_both') & pl.col('branch').eq('refactored'))

shape: (1_348, 10)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬───────────┬─────────┐
│ _from      ┆ _to        ┆ from       ┆ to        ┆ … ┆ resemblin ┆ type    ┆ branch    ┆ in_both │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ g         ┆ ---     ┆ ---       ┆ ---     │
│ str        ┆ str        ┆ str        ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ bool    │
│            ┆            ┆            ┆           ┆   ┆ bool      ┆         ┆           ┆         │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═════════╡
│ super_nav_ ┆ super_nav_ ┆ an1.219-23 ┆ mil5.5.3# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/mi ┆ 4#1.1      ┆ 1.1       ┆   ┆           ┆         ┆ d         ┆         │
│ 1.219-234  ┆ l5.5.3     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an1.616#1. ┆ mil6.4.1# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/mi ┆ 1          ┆ 20.1      ┆   ┆           ┆         ┆ d         ┆         │
│ 1.616-627  ┆ l6.4.1     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an10.89#1. ┆ ne37#53.1 ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/ne ┆ 1-#10.1    ┆ -#58.1    ┆   ┆           ┆         ┆ d         ┆         │
│ 10.89      ┆ 37         ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an3.131#1. ┆ mil5.4.2# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/mi ┆ 1-#2.1     ┆ 1.1       ┆   ┆           ┆         ┆ d         ┆         │
│ 3.131      ┆ l5.4.2     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an3.36#13. ┆ mil3.4.6# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/an ┆ details/mi ┆ 1-#15.1    ┆ 2.1       ┆   ┆           ┆         ┆ d         ┆         │
│ 3.36       ┆ l3.4.6     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …       │
│ super_nav_ ┆ super_nav_ ┆ uvs7#uvs7. ┆ mil5.3.3# ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/uv ┆ details/mi ┆ 7          ┆ 2.1       ┆   ┆           ┆         ┆ d         ┆         │
│ s7         ┆ l5.3.3     ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bi- ┆ kv21.4#6. ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/xc ┆ details/kv ┆ pm-np19    ┆ 1         ┆   ┆           ┆         ┆ d         ┆         │
│ t-mu-bi-pm ┆ 21.4       ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆            ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bi- ┆ kv21.4#6. ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/xc ┆ details/kv ┆ vb-np19    ┆ 1         ┆   ┆           ┆         ┆ d         ┆         │
│ t-mu-bi-vb ┆ 21.4       ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆            ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ kv21.4#6. ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/xc ┆ details/kv ┆ pm-np30    ┆ 1         ┆   ┆           ┆         ┆ d         ┆         │
│ t-mu-bu-pm ┆ 21.4       ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆            ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ kv21.4#6. ┆ … ┆ true      ┆ mention ┆ refactore ┆ false   │
│ details/xc ┆ details/kv ┆ vb-np30    ┆ 1         ┆   ┆           ┆         ┆ d         ┆         │
│ t-mu-bu-vb ┆ 21.4       ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
│ …          ┆            ┆            ┆           ┆   ┆           ┆         ┆           ┆         │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴───────────┴─────────┘

In [7]:
df.filter(
    ~pl.col('in_both')
).filter(
    pl.col('branch').eq('refactored') & ~(pl.col('resembling') & pl.col('type').eq('mention'))
)

shape: (0, 10)
┌───────┬─────┬──────┬─────┬───┬────────────┬──────┬────────┬─────────┐
│ _from ┆ _to ┆ from ┆ to  ┆ … ┆ resembling ┆ type ┆ branch ┆ in_both │
│ ---   ┆ --- ┆ ---  ┆ --- ┆   ┆ ---        ┆ ---  ┆ ---    ┆ ---     │
│ str   ┆ str ┆ str  ┆ str ┆   ┆ bool       ┆ str  ┆ str    ┆ bool    │
╞═══════╪═════╪══════╪═════╪═══╪════════════╪══════╪════════╪═════════╡
└───────┴─────┴──────┴─────┴───┴────────────┴──────┴────────┴─────────┘

In [8]:
df.filter(
    ~pl.col('in_both') & pl.col('branch').eq('refactored')
).group_by(['type', 'resembling']).len()

shape: (1, 3)
┌─────────┬────────────┬──────┐
│ type    ┆ resembling ┆ len  │
│ ---     ┆ ---        ┆ ---  │
│ str     ┆ bool       ┆ u32  │
╞═════════╪════════════╪══════╡
│ mention ┆ true       ┆ 1348 │
└─────────┴────────────┴──────┘

In [9]:
df.filter(~pl.col('in_both') & pl.col('branch').eq('main') & pl.col('_to').str.contains('orphan'))

shape: (0, 10)
┌───────┬─────┬──────┬─────┬───┬────────────┬──────┬────────┬─────────┐
│ _from ┆ _to ┆ from ┆ to  ┆ … ┆ resembling ┆ type ┆ branch ┆ in_both │
│ ---   ┆ --- ┆ ---  ┆ --- ┆   ┆ ---        ┆ ---  ┆ ---    ┆ ---     │
│ str   ┆ str ┆ str  ┆ str ┆   ┆ bool       ┆ str  ┆ str    ┆ bool    │
╞═══════╪═════╪══════╪═════╪═══╪════════════╪══════╪════════╪═════════╡
└───────┴─────┴──────┴─────┴───┴────────────┴──────┴────────┴─────────┘

In [10]:
df.filter(pl.col('_from').str.contains('kv14.8') & ~pl.col('in_both'))

shape: (2, 10)
┌─────────────┬─────────────┬────────────┬───────────┬───┬────────────┬─────────┬────────┬─────────┐
│ _from       ┆ _to         ┆ from       ┆ to        ┆ … ┆ resembling ┆ type    ┆ branch ┆ in_both │
│ ---         ┆ ---         ┆ ---        ┆ ---       ┆   ┆ ---        ┆ ---     ┆ ---    ┆ ---     │
│ str         ┆ str         ┆ str        ┆ str       ┆   ┆ bool       ┆ str     ┆ str    ┆ bool    │
╞═════════════╪═════════════╪════════════╪═══════════╪═══╪════════════╪═════════╪════════╪═════════╡
│ super_nav_d ┆ super_nav_d ┆ kv14.8#8.1 ┆ sa787-788 ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/kv14 ┆ etails/sa78 ┆            ┆           ┆   ┆            ┆         ┆        ┆         │
│ .8          ┆ 7           ┆            ┆           ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_d ┆ kv14.8#8.1 ┆ sa787-788 ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/kv14 ┆ etails/sa78 ┆            ┆           ┆   ┆            ┆         ┆        ┆         │
│ .8          ┆ 8           ┆            ┆           ┆   ┆            ┆         ┆        ┆         │
└─────────────┴─────────────┴────────────┴───────────┴───┴────────────┴─────────┴────────┴─────────┘

In [11]:
df.filter(pl.col('_from').str.contains('lzh-dg-bi-pm-sk36')).group_by(pl.col('in_both')).len()

shape: (1, 2)
┌─────────┬─────┐
│ in_both ┆ len │
│ ---     ┆ --- │
│ bool    ┆ u32 │
╞═════════╪═════╡
│ true    ┆ 144 │
└─────────┴─────┘

We have orphans

In [13]:
df.filter(pl.col('_to').str.ends_with('orphan'))

shape: (33_756, 10)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬──────┬────────────┬─────────┐
│ _from      ┆ _to        ┆ from       ┆ to         ┆ … ┆ resembling ┆ type ┆ branch     ┆ in_both │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---  ┆ ---        ┆ ---     │
│ str        ┆ str        ┆ str        ┆ str        ┆   ┆ bool       ┆ str  ┆ str        ┆ bool    │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪══════╪════════════╪═════════╡
│ super_nav_ ┆ super_nav_ ┆ dhp3       ┆ Mūlasarvās ┆ … ┆ false      ┆ full ┆ main       ┆ true    │
│ details/dh ┆ details/or ┆            ┆ tivādivina ┆   ┆            ┆      ┆            ┆         │
│ p1-20      ┆ phan       ┆            ┆ ya         ┆   ┆            ┆      ┆            ┆         │
│            ┆            ┆            ┆ (Gilgit…   ┆   ┆            ┆      ┆            ┆         │
│ super_nav_ ┆ super_nav_ ┆ dhp4       ┆ Mūlasarvās ┆ … ┆ false      ┆ full ┆ main       ┆ true    │
│ details/dh ┆ details/or ┆            ┆ tivādivina ┆   ┆            ┆      ┆            ┆         │
│ p1-20      ┆ phan       ┆            ┆ ya         ┆   ┆            ┆      ┆            ┆         │
│            ┆            ┆            ┆ (Gilgit…   ┆   ┆            ┆      ┆            ┆         │
│ super_nav_ ┆ super_nav_ ┆ dhp5       ┆ Mūlasarvās ┆ … ┆ false      ┆ full ┆ main       ┆ true    │
│ details/dh ┆ details/or ┆            ┆ tivādivina ┆   ┆            ┆      ┆            ┆         │
│ p1-20      ┆ phan       ┆            ┆ ya         ┆   ┆            ┆      ┆            ┆         │
│            ┆            ┆            ┆ (Gilgit…   ┆   ┆            ┆      ┆            ┆         │
│ super_nav_ ┆ super_nav_ ┆ dhp6       ┆ Mūlasarvās ┆ … ┆ false      ┆ full ┆ main       ┆ true    │
│ details/dh ┆ details/or ┆            ┆ tivādivina ┆   ┆            ┆      ┆            ┆         │
│ p1-20      ┆ phan       ┆            ┆ ya         ┆   ┆            ┆      ┆            ┆         │
│            ┆            ┆            ┆ (Gilgit…   ┆   ┆            ┆      ┆            ┆         │
│ super_nav_ ┆ super_nav_ ┆ dhp103     ┆ Uttarādhya ┆ … ┆ false      ┆ full ┆ main       ┆ true    │
│ details/dh ┆ details/or ┆            ┆ yanasūtra  ┆   ┆            ┆      ┆            ┆         │
│ p100-115   ┆ phan       ┆            ┆ 9#34       ┆   ┆            ┆      ┆            ┆         │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …    ┆ …          ┆ …       │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ Bhikkhu    ┆ … ┆ false      ┆ full ┆ refactored ┆ true    │
│ details/xc ┆ details/or ┆ vb-ss7     ┆ Parivāra   ┆   ┆            ┆      ┆            ┆         │
│ t-mu-bu-vb ┆ phan       ┆            ┆ Saṅghādise ┆   ┆            ┆      ┆            ┆         │
│ …          ┆            ┆            ┆ sa …       ┆   ┆            ┆      ┆            ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ Bhikkhu    ┆ … ┆ false      ┆ full ┆ refactored ┆ true    │
│ details/xc ┆ details/or ┆ vb-ss8     ┆ Parivāra   ┆   ┆            ┆      ┆            ┆         │
│ t-mu-bu-vb ┆ phan       ┆            ┆ Saṅghādise ┆   ┆            ┆      ┆            ┆         │
│ …          ┆            ┆            ┆ sa …       ┆   ┆            ┆      ┆            ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ Bhikkhunī  ┆ … ┆ false      ┆ full ┆ refactored ┆ true    │
│ details/xc ┆ details/or ┆ vb-ss8     ┆ Parivāra   ┆   ┆            ┆      ┆            ┆         │
│ t-mu-bu-vb ┆ phan       ┆            ┆ Saṅghādise ┆   ┆            ┆      ┆            ┆         │
│ …          ┆            ┆            ┆ s…         ┆   ┆            ┆      ┆            ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ Bhikkhu    ┆ … ┆ false      ┆ full ┆ refactored ┆ true    │
│ details/xc ┆ details/or ┆ vb-ss9     ┆ Parivāra   ┆   ┆            ┆      ┆            ┆         │
│ t-mu-bu-vb ┆ phan       ┆            ┆ Saṅghādise ┆   ┆            ┆      ┆            ┆         │
│ …          ┆            ┆            ┆ sa …       ┆   ┆            ┆      ┆            ┆         │
│ super_nav_ ┆ super_nav_ ┆ xct-mu-bu- ┆ Bhikkhunī  ┆ … ┆ false      ┆ full ┆ refactored ┆ true    │
│ details/xc ┆ details/or ┆ vb-ss9     ┆ Parivāra   ┆   ┆            ┆      ┆            ┆         │
│ t-mu-bu-vb ┆ phan       ┆            ┆ Saṅghādise ┆   ┆            ┆      ┆            ┆         │
│ …          ┆            ┆            ┆ s…         ┆   ┆            ┆      ┆            ┆         │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴──────┴────────────┴─────────┘

Edges that are only in `main` and don't have `to` or `from` starting with tildes.

In [22]:
df.filter(
    pl.col('branch').eq('main') & ~pl.col('in_both')
).filter(
    ~(pl.col('from').str.starts_with('~') | pl.col('to').str.starts_with('~'))
)

shape: (116, 10)
┌─────────────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬────────┬─────────┐
│ _from       ┆ _to        ┆ from       ┆ to         ┆ … ┆ resembling ┆ type    ┆ branch ┆ in_both │
│ ---         ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---     ┆ ---    ┆ ---     │
│ str         ┆ str        ┆ str        ┆ str        ┆   ┆ bool       ┆ str     ┆ str    ┆ bool    │
╞═════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════╪═════════╡
│ super_nav_d ┆ super_nav_ ┆ an7.75-78  ┆ pli-tv-pvr ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an7. ┆ details/pl ┆            ┆ 7#97.1-#10 ┆   ┆            ┆         ┆        ┆         │
│ 76          ┆ i-tv-pvr7  ┆            ┆ 0.1        ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an7.75-78  ┆ pli-tv-pvr ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an7. ┆ details/pl ┆            ┆ 7#97.1-#10 ┆   ┆            ┆         ┆        ┆         │
│ 77          ┆ i-tv-pvr7  ┆            ┆ 0.1        ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ an7.75-78  ┆ pli-tv-pvr ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/an7. ┆ details/pl ┆            ┆ 7#97.1-#10 ┆   ┆            ┆         ┆        ┆         │
│ 78          ┆ i-tv-pvr7  ┆            ┆ 0.1        ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ kv1.9#11.1 ┆ sa721-722  ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/kv1. ┆ details/sa ┆ -#12.1     ┆            ┆   ┆            ┆         ┆        ┆         │
│ 9           ┆ 721        ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ kv1.9#11.1 ┆ sa721-722  ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/kv1. ┆ details/sa ┆ -#12.1     ┆            ┆   ┆            ┆         ┆        ┆         │
│ 9           ┆ 722        ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ …           ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …       ┆ …      ┆ …       │
│ super_nav_d ┆ super_nav_ ┆ ud5.6#18.1 ┆ snp4.1-16  ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/ud5. ┆ details/sn ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ 6           ┆ p4.5       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ ud5.6#18.1 ┆ snp4.1-16  ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/ud5. ┆ details/sn ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ 6           ┆ p4.6       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ ud5.6#18.1 ┆ snp4.1-16  ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/ud5. ┆ details/sn ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ 6           ┆ p4.7       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ ud5.6#18.1 ┆ snp4.1-16  ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/ud5. ┆ details/sn ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ 6           ┆ p4.8       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ super_nav_d ┆ super_nav_ ┆ ud5.6#18.1 ┆ snp4.1-16  ┆ … ┆ false      ┆ mention ┆ main   ┆ false   │
│ etails/ud5. ┆ details/sn ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
│ 6           ┆ p4.9       ┆            ┆            ┆   ┆            ┆         ┆        ┆         │
└─────────────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴────────┴─────────┘

Is this one missing from `refactored`?

https://github.com/suttacentral/sc-data/blob/7855ada307e9679b373bbcf8152f0c09ec072b81/relationship/parallels.json#L68474-L68479

```json
    {
        "mentions": [
            "an7.75-78",
            "pli-tv-pvr7#97.1-#100.1"
        ]
    },
```

In [26]:
df.filter(
    pl.col('branch').eq('refactored') & pl.col('from').eq('an7.75-78')
)

shape: (1, 10)
┌────────────┬────────────┬───────────┬────────────┬───┬───────────┬─────────┬───────────┬─────────┐
│ _from      ┆ _to        ┆ from      ┆ to         ┆ … ┆ resemblin ┆ type    ┆ branch    ┆ in_both │
│ ---        ┆ ---        ┆ ---       ┆ ---        ┆   ┆ g         ┆ ---     ┆ ---       ┆ ---     │
│ str        ┆ str        ┆ str       ┆ str        ┆   ┆ ---       ┆ str     ┆ str       ┆ bool    │
│            ┆            ┆           ┆            ┆   ┆ bool      ┆         ┆           ┆         │
╞════════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪═════════╪═══════════╪═════════╡
│ super_nav_ ┆ super_nav_ ┆ an7.75-78 ┆ pli-tv-pvr ┆ … ┆ false     ┆ mention ┆ refactore ┆ true    │
│ details/an ┆ details/pl ┆           ┆ 7#97.1-#10 ┆   ┆           ┆         ┆ d         ┆         │
│ 7.75       ┆ i-tv-pvr7  ┆           ┆ 0.1        ┆   ┆           ┆         ┆           ┆         │
└────────────┴────────────┴───────────┴────────────┴───┴───────────┴─────────┴───────────┴─────────┘

So there are some missing in the expansion?

In [33]:
df.filter(
    pl.col('from').eq('an7.75-78')
).sort('_from')

shape: (5, 10)
┌────────────┬────────────┬───────────┬────────────┬───┬───────────┬─────────┬───────────┬─────────┐
│ _from      ┆ _to        ┆ from      ┆ to         ┆ … ┆ resemblin ┆ type    ┆ branch    ┆ in_both │
│ ---        ┆ ---        ┆ ---       ┆ ---        ┆   ┆ g         ┆ ---     ┆ ---       ┆ ---     │
│ str        ┆ str        ┆ str       ┆ str        ┆   ┆ ---       ┆ str     ┆ str       ┆ bool    │
│            ┆            ┆           ┆            ┆   ┆ bool      ┆         ┆           ┆         │
╞════════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪═════════╪═══════════╪═════════╡
│ super_nav_ ┆ super_nav_ ┆ an7.75-78 ┆ pli-tv-pvr ┆ … ┆ false     ┆ mention ┆ main      ┆ true    │
│ details/an ┆ details/pl ┆           ┆ 7#97.1-#10 ┆   ┆           ┆         ┆           ┆         │
│ 7.75       ┆ i-tv-pvr7  ┆           ┆ 0.1        ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an7.75-78 ┆ pli-tv-pvr ┆ … ┆ false     ┆ mention ┆ refactore ┆ true    │
│ details/an ┆ details/pl ┆           ┆ 7#97.1-#10 ┆   ┆           ┆         ┆ d         ┆         │
│ 7.75       ┆ i-tv-pvr7  ┆           ┆ 0.1        ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an7.75-78 ┆ pli-tv-pvr ┆ … ┆ false     ┆ mention ┆ main      ┆ false   │
│ details/an ┆ details/pl ┆           ┆ 7#97.1-#10 ┆   ┆           ┆         ┆           ┆         │
│ 7.76       ┆ i-tv-pvr7  ┆           ┆ 0.1        ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an7.75-78 ┆ pli-tv-pvr ┆ … ┆ false     ┆ mention ┆ main      ┆ false   │
│ details/an ┆ details/pl ┆           ┆ 7#97.1-#10 ┆   ┆           ┆         ┆           ┆         │
│ 7.77       ┆ i-tv-pvr7  ┆           ┆ 0.1        ┆   ┆           ┆         ┆           ┆         │
│ super_nav_ ┆ super_nav_ ┆ an7.75-78 ┆ pli-tv-pvr ┆ … ┆ false     ┆ mention ┆ main      ┆ false   │
│ details/an ┆ details/pl ┆           ┆ 7#97.1-#10 ┆   ┆           ┆         ┆           ┆         │
│ 7.78       ┆ i-tv-pvr7  ┆           ┆ 0.1        ┆   ┆           ┆         ┆           ┆         │
└────────────┴────────────┴───────────┴────────────┴───┴───────────┴─────────┴───────────┴─────────┘

Yes - the mention isn't expanded on the `refactored` branch